### ISSUE TITLE
No license listed

### ISSUE THREAD

**Issue by jmgrosen** [ms-jpq/gay#1]
I'd like to be able to download this (and perhaps add it to nixpkgs), but there's no license listed! Could you add a LICENSE file with your favorite in there and list it in the README as well?

**Comment by ms-jpq** [comment]
no problem, do you know which is the "best" license?

I have zero clue on which one is the most "open" or whatever, I just want everybody to be able to use it

**Comment by jmgrosen** [comment]
I'd personally use the MIT license -- it basically says "do whatever you
want, just don't sue me if it messes you up."

**Comment by ms-jpq** [comment]
done

[https://github.com/ms-jpq/gay/blob/%3C3/LICENSE](https://github.com/ms-jpq/gay/blob/%3C3/LICENSE)

:D
