### ISSUE TITLE
Smoother transition between terminal lines

### ISSUE THREAD

**Issue by nshepperd** [ms-jpq/gay#2]
`lolcat` maps its rainbow gradient into the 2d dimensions of the terminal smoothly, so that neighbouring lines get similar colours. For example (comparison):

![screenshot](https://user-images.githubusercontent.com/406019/86284734-6a955b00-bbb1-11ea-82c4-db34510b6e49.png)

It would be nice to do the same thing lolcat does, to have it look something like this instead:

![screenshot](https://user-images.githubusercontent.com/406019/86286685-ea70f480-bbb4-11ea-856a-060f5f474a3d.png)

This probably means switching from the generator-based rgb_gen to some sort of function of terminal coodinates.

**Comment by ms-jpq** [comment]
good idea, righ now im just using a random number to demarcate the transition boundaries,

**Comment by nshepperd** [comment]
I hacked up something that works pretty well: https://github.com/nshepperd/gay/commit/c78935c388d54da3c964fbbe8d93046d68534fd0

**Comment by ms-jpq** [comment]
oh hey thank you, i will go take a look slightly later today :D 

thank you so much!

**Comment by ms-jpq** [comment]
Finally made it happen, thank you so much

https://github.com/ms-jpq/gay/commit/70b508ff463d7e9e882efe2f86516c1c1a726729

I added a flag `-i {1d,2d}, --interpolation {1d,2d}`, where `1d` was the old algo, and `2d` is your algo

Gonna release this after I test it a bit more :D
