### ISSUE TITLE
dataclasses not installed by pip

### ISSUE THREAD

**Issue by Masterchef365** [ms-jpq/gay#3]
Installed via `pip3 install --user gay`, then ran `gay -h | gay` and got the following trace:
```
Traceback (most recent call last):
  File "/home/duncan/.local/bin/gay", line 6, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
Traceback (most recent call last):
  File "/home/duncan/.local/bin/gay", line 6, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```
So I went ahead and installed dataclasses with `pip3 install --user dataclasses`, which fixed it.

**Comment by ms-jpq** [comment]
Ohh, are you on python version < 3.7?

I thought they were EOL already?

I can either rewrite the code to not use dataclasses or add a line to `README`.

Idk how many people still use EOL python tho

**Comment by Masterchef365** [comment]
I'm using Python 3.6.9, as it's the version that Ubuntu 18.04 LTS ships with

**Comment by ms-jpq** [comment]
Thanks, I thought 18.04 came with python 3.7.

I took out the dep in this commit https://github.com/ms-jpq/gay/commit/3c0b4c0209e927b719e92818986da80376f109c1

Gonna release it with a new interpolation mode later today
